SUPABASE_URL = "https://igrapzdlyupdvrevnxlk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlncmFwemRseXVwZHZyZXZueGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0OTgzNjIsImV4cCI6MjA3NjA3NDM2Mn0.rzfL6yeXJgEkiEHZPA9dNUxdzpZsuvqmUFcYTvG05fA"
